const DATA_FILES={funnel:'data/home_funnel_requested_fields.json',sections:'data/home_sections_risk_detail.json',banners:'data/banner_click_detail.json',guess:'data/recommend_data_20260909.json',pv:'data/guess_you_like_pv_home_data.json'};
const CHANNELS=['精选','电影','美剧','英剧','韩剧','日剧','泰剧','国产剧'];
const state={start:'2026-09-09',end:'2026-09-09',client:'all',sortAsc:false,rows:{}};
const $=id=>document.getElementById(id);
const fmt=n=>n==null||n===''?'暂无真实快照数据':Number(n).toLocaleString('zh-CN');
const pct=n=>n==null||n===''?'暂无真实快照数据':`${(Number(n)*100).toFixed(2)}%`;
function repair(value){if(typeof value==='string'&&/[ÃÂåæçéèï]/.test(value)){try{return decodeURIComponent(escape(value))}catch{return value}}if(Array.isArray(value))return value.map(repair);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,repair(v)]));return value}
async function loadFile(path){const r=await fetch(path);if(!r.ok)throw new Error(path);return repair(await r.json())}
function rows(name){return state.rows[name]||[]}
function active(list){return list.filter(r=>(!state.start||r.date>=state.start)&&(!state.end||r.date<=state.end)&& (state.client==='all'||r.client===state.client))}
function tableEmpty(colspan=4){return `<tr><td class="empty-row" colspan="${colspan}">暂无真实快照数据</td></tr>`}
function exactDate(){return state.end||'2026-08-04'}
function renderOverview(){['channel','section','banner','guess'].forEach(id=>$("kpi-"+id).classList.add('empty'));let current=exactDate();let f=rows('funnel').filter(r=>r.date===current&&(state.client==='all'||r.client===state.client));let s=rows('sections').filter(r=>r.date===current&&(state.client==='all'||r.client===state.client));let b=rows('banners').filter(r=>r.date===current&&(state.client==='all'||r.client===state.client));let g=rows('guess').filter(r=>r.date===current&&(state.client==='all'||r.client===state.client));
  // Cards only render an exact snapshot row; no dimension rollups are created here.
  const exact=[['channel',f.find(r=>r.channel==='精选'&&r.device==='老设备')?.homepage_channel_click_uv],['section',s.find(r=>!r.sub_board_name)?.click_uv],['banner',b[0]?.click_uv],['guess',g[0]?.content_click_uv]];
  exact.forEach(([id,val])=>{if(val!=null){$("kpi-"+id).textContent=fmt(val);$("kpi-"+id).classList.remove('empty')}});$('filter-status').textContent=`${current} · ${state.client==='all'?'全部客户端':state.client}`}
function renderChannel(){let list=active(rows('funnel')).filter(r=>CHANNELS.includes(r.channel));let selected=list.filter(r=>r.date===exactDate());let latestByChannel=CHANNELS.map(channel=>selected.find(r=>r.channel===channel&&r.device==='老设备')||selected.find(r=>r.channel===channel)).filter(Boolean);let max=Math.max(...latestByChannel.map(r=>Number(r.homepage_channel_click_uv)||0),1);let first=latestByChannel.find(r=>r.channel==='精选');let funnel=first?[['首页频道点击UV',first.homepage_channel_click_uv,'homepage_channel_click_uv'],['内容点击UV',first.content_click_uv,'content_click_uv'],['详情播放UV',first.detail_play_uv,'detail_play_uv']]:[];$('funnel-list').innerHTML=funnel.length?funnel.map(([label,val,field])=>`<div class="funnel-row"><div class="funnel-label">${label}<small>${field}</small></div><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,Number(val)/Math.max(Number(funnel[0][1]),1)*100)}%"></div></div><div class="funnel-value">${fmt(val)}</div></div>`).join(''):tableEmpty(3);let sorted=[...latestByChannel].sort((a,b)=>(Number(b.homepage_channel_click_uv)-Number(a.homepage_channel_click_uv))*(state.sortAsc?-1:1));$('channel-table').innerHTML=sorted.length?sorted.map(r=>`<tr><td>${r.channel}</td><td>${fmt(r.homepage_channel_click_uv)}</td></tr>`).join(''):tableEmpty(2)}
function sectionRows(){return active(rows('sections')).filter(r=>r.application_name==='新人人视频'&&CHANNELS.includes(r.board_name)&&r.sub_board_name)}
function renderSections(){let list=sectionRows().filter(r=>r.date===exactDate());let boards=[];let seen=new Set();list.forEach(r=>{if(!seen.has(r.board_name)){seen.add(r.board_name);boards.push(r)}});boards.sort((a,b)=>Number(b.click_ctr_uv||0)-Number(a.click_ctr_uv||0));$('section-table').innerHTML=boards.length?boards.map((r,i)=>`<tr><td>${r.board_name}</td><td>${fmt(r.exposure_uv)}</td><td>${fmt(r.click_uv)}</td><td>${pct(r.click_ctr_uv)}</td><td><button class="ghost expand-section" data-board="${r.board_name}">查看子板块</button></td></tr>`).join(''):tableEmpty(5);document.querySelectorAll('.expand-section').forEach(btn=>btn.addEventListener('click',()=>showSubsections(btn.dataset.board)));let chartRows=boards.slice(0,10).reverse();if(window.echarts){let chart=echarts.init($('section-chart'));chart.setOption({grid:{left:120,right:18,top:12,bottom:18},xAxis:{type:'value',axisLabel:{formatter:v=>(v*100).toFixed(0)+'%',color:'#8190a4'},splitLine:{lineStyle:{color:'#edf1f6'}}},yAxis:{type:'category',data:chartRows.map(r=>r.board_name),axisLabel:{color:'#52627a'}},series:[{type:'bar',data:chartRows.map(r=>r.click_ctr_uv),barWidth:12,itemStyle:{color:'#4b8bea',borderRadius:[0,5,5,0]}}],tooltip:{trigger:'axis',valueFormatter:v=>(v*100).toFixed(2)+'%'}})}}
function showSubsections(board){let list=sectionRows().filter(r=>r.date===exactDate()&&r.board_name===board);$('subsection').hidden=false;$('subsection-title').textContent=`${board} · 子板块`;let body=list.length?`<div class="table-wrap"><table><thead><tr><th>子板块名称</th><th>曝光UV</th><th>点击UV</th><th>UV点击率</th></tr></thead><tbody>${list.slice(0,80).map(r=>`<tr><td>${r.sub_board_name||'暂无子板块数据'}</td><td>${fmt(r.exposure_uv)}</td><td>${fmt(r.click_uv)}</td><td>${pct(r.click_ctr_uv)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-row">暂无子板块数据</div>';$('subsection-body').innerHTML=body;$('section-selection').textContent=board}
function bannerRows(){return active(rows('banners')).filter(r=>r.date===exactDate()&&r.channel&&CHANNELS.includes(r.channel)).sort((a,b)=>Number(b.ctr_uv||0)-Number(a.ctr_uv||0))}
function renderBanners(){let list=bannerRows();$('banner-table').innerHTML=list.length?list.slice(0,50).map(r=>`<tr><td title="${r.title||''}">${r.title||'暂无标题'}</td><td>${r.banner_position||'—'}</td><td>${r.channel}</td><td>${fmt(r.exposure_uv)}</td><td>${fmt(r.click_uv)}</td><td>${pct(r.ctr_uv)}</td></tr>`).join(''):tableEmpty(6);let chartRows=list.slice(0,10).reverse();if(window.echarts){let chart=echarts.init($('banner-chart'));chart.setOption({grid:{left:160,right:18,top:12,bottom:18},xAxis:{type:'value',axisLabel:{formatter:v=>(v*100).toFixed(0)+'%',color:'#8190a4'},splitLine:{lineStyle:{color:'#edf1f6'}}},yAxis:{type:'category',data:chartRows.map(r=>(r.title||'暂无标题').slice(0,18)),axisLabel:{color:'#52627a'}},series:[{type:'bar',data:chartRows.map(r=>r.ctr_uv),barWidth:12,itemStyle:{color:'#7ca8ed',borderRadius:[0,5,5,0]}}],tooltip:{trigger:'axis',valueFormatter:v=>(v*100).toFixed(2)+'%'}})}}
function renderGuess(){
  const list=active(rows('guess')).filter(r=>r.client==='安卓'||state.client==='all');
  const byDate=list.sort((a,b)=>a.date.localeCompare(b.date));
  const latest=list[list.length-1];
  const metrics=[['点击','content_click_uv'],['播放','play_uv'],['播放超过5分钟','play_over_5m_uv'],['有效播放','effective_play_uv']];
  $('guess-kpi-list').innerHTML=latest?metrics.map(([label,key])=>`<div class="mini-kpi"><span>${label}</span><strong>${fmt(latest[key])}</strong></div>`).join(''):tableEmpty(2);
  if(!window.echarts)return;
  const chart=echarts.init($('guess-chart'));
  chart.setOption({
    grid:{left:48,right:18,top:18,bottom:32},
    legend:{top:0,textStyle:{color:'#77859a'}},
    xAxis:{type:'category',data:byDate.map(r=>r.date.slice(5)),axisLabel:{color:'#8190a4'}},
    yAxis:{type:'value',axisLabel:{color:'#8190a4'},splitLine:{lineStyle:{color:'#edf1f6'}}},
    tooltip:{trigger:'axis'},
    series:metrics.map(([label,key],i)=>({name:label,type:'line',smooth:true,data:byDate.map(r=>r[key]),symbol:'circle',symbolSize:5,lineStyle:{width:2},itemStyle:{color:['#2f76e8','#5da6ed','#45ad83','#e4a24c'][i]}}))
  });
}
function render(){renderOverview();renderChannel();renderSections();renderBanners();renderGuess()}
async function init(){try{const data=await Promise.all(Object.entries(DATA_FILES).map(async([key,path])=>[key,(await loadFile(path)).rows||[]]));data.forEach(([key,value])=>state.rows[key]=value);$('apply-filter').addEventListener('click',()=>{state.start=$('date-start').value;state.end=$('date-end').value;state.client=$('client-filter').value;render()});$('sort-channel').addEventListener('click',()=>{state.sortAsc=!state.sortAsc;renderChannel()});$('close-subsection').addEventListener('click',()=>{$('subsection').hidden=true});render()}catch(error){document.querySelectorAll('.kpi-card strong').forEach(el=>{el.textContent='暂无真实快照数据';el.classList.add('empty')});$('filter-status').textContent='本地快照加载失败'}}
init();
