<script setup lang="ts">
import {computed,defineAsyncComponent,onMounted,ref} from "vue";import {InfoFilled,RefreshRight} from "@element-plus/icons-vue";import {useRoute,useRouter} from "vue-router";
import {fetchHomeOperations,type HomePayload} from "../api/homeOperations";import {useThemeStore} from "../stores/theme";
const Chart=defineAsyncComponent(()=>import("../components/OverviewTrendChart.vue"));const route=useRoute(),router=useRouter(),theme=useThemeStore();const tab=ref(route.query.tab==="guess"?"guess":"channel"),date=ref(typeof route.query.date==="string"?route.query.date:(tab.value==="guess"?"2026-09-15":"2026-08-04")),range=ref<[string,string]>(["2026-09-09","2026-09-15"]),data=ref<HomePayload|null>(null),loading=ref(false),error=ref(""),drawer=ref(false);const nf=new Intl.NumberFormat("zh-CN");const num=(v:number|null|undefined)=>v==null?"--":nf.format(v);const pct=(v:number|null|undefined)=>v==null?"--":`${(v*100).toFixed(2)}%`;
async function load(){loading.value=true;error.value="";router.replace({query:{tab:tab.value,date:date.value}});try{data.value=await fetchHomeOperations(date.value,range.value[0],range.value[1])}catch(e){error.value="首页运营数据加载失败。";console.error(e)}finally{loading.value=false}}
function switchTab(v:string){tab.value=v;date.value=v==="guess"?"2026-09-15":"2026-08-04";load()}
const channelChart=computed(()=>({color:[theme.current.primary],grid:{left:100,right:25,top:15,bottom:25},tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},xAxis:{type:"value"},yAxis:{type:"category",data:data.value?.channels.slice().reverse().map(x=>x.channel)??[]},series:[{type:"bar",data:data.value?.channels.slice().reverse().map(x=>x.entry_uv)??[],barMaxWidth:18}]}));
const guessChart=computed(()=>({color:[theme.current.primary,theme.current.secondary],tooltip:{trigger:"axis"},legend:{top:4},grid:{left:65,right:24,top:42,bottom:30},xAxis:{type:"category",data:data.value?.recommendation_trend.map(x=>x.date.slice(5))??[]},yAxis:{type:"value"},series:[{name:"内容曝光 UV",type:"line",smooth:true,data:data.value?.recommendation_trend.map(x=>x.content_exposure_uv)??[]},{name:"内容点击 UV",type:"line",smooth:true,data:data.value?.recommendation_trend.map(x=>x.content_click_uv)??[]}]}));onMounted(load);
</script>
<template><main class="main-content page-stack"><header class="page-intro"><div><h2>首页运营</h2><p>首页频道导流与猜你喜欢推荐效率。</p></div><button class="source-button" @click="drawer=true"><el-icon><InfoFilled/></el-icon>数据说明</button></header><section class="filter-bar ranking-filter"><div class="ranking-tabs" role="tablist"><button role="tab" :class="{active:tab==='channel'}" @click="switchTab('channel')">首页频道</button><button role="tab" :class="{active:tab==='guess'}" @click="switchTab('guess')">猜你喜欢</button></div><label><span>数据日期</span><el-date-picker v-model="date" type="date" value-format="YYYY-MM-DD"/></label><el-button type="primary" :loading="loading" @click="load"><el-icon><RefreshRight/></el-icon>更新视图</el-button><div class="freshness"><span class="status-dot"></span><div><b>真实快照</b><small>{{tab==='channel'?data?.meta.channel.source:data?.meta.recommendation.source}}</small></div></div></section><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"/>
<template v-if="tab==='channel'"><section class="metric-grid home-metrics"><article v-for="item in [['频道数量',data?.channels.length,'当前日期'],['入口 UV',data?.channels[0]?.entry_uv,'最高频道'],['内容点击 UV',data?.channels[0]?.content_click_uv,'最高入口频道'],['详情播放 UV',data?.channels[0]?.detail_play_uv,'最高入口频道'],['有效播放 UV',data?.channels[0]?.effective_play_uv,'最高入口频道']]" :key="String(item[0])" class="metric-item"><div class="metric-label"><span>{{item[0]}}</span><small>{{item[2]}}</small></div><strong>{{item[0]==='频道数量'?`${item[1]??0} 个`:num(item[1] as number)}}</strong></article></section><section class="content-grid"><article class="panel"><div class="panel-head"><div><h2>频道入口排行</h2><p>首页进入频道页 UV</p></div></div><Chart class="resource-chart" :option="channelChart"/></article><article class="panel ranking-note"><div class="panel-head"><div><h2>链路说明</h2><p>原始UV口径</p></div></div><dl><div><dt>入口</dt><dd>首页进入频道页</dd></div><div><dt>点击</dt><dd>频道页内容点击</dd></div><div><dt>播放</dt><dd>详情播放</dd></div><div><dt>深度消费</dt><dd>5分钟及有效播放</dd></div></dl></article></section><section class="panel ranking-detail-panel"><div class="panel-head"><div><h2>频道明细</h2><p>不计算虚拟流失率</p></div></div><div class="table-wrap"><table class="client-table"><thead><tr><th>频道</th><th>入口UV</th><th>内容点击UV</th><th>详情播放UV</th><th>5分钟UV</th><th>有效播放UV</th><th>入口点击率</th><th>点击播放率</th></tr></thead><tbody><tr v-for="x in data?.channels" :key="x.channel"><td><strong>{{x.channel}}</strong></td><td>{{num(x.entry_uv)}}</td><td>{{num(x.content_click_uv)}}</td><td>{{num(x.detail_play_uv)}}</td><td>{{num(x.play_5m_uv)}}</td><td>{{num(x.effective_play_uv)}}</td><td>{{pct(x.entry_click_rate)}}</td><td>{{pct(x.click_play_rate)}}</td></tr></tbody></table></div></section></template>
<template v-else><section class="ranking-summary-grid"><article v-for="item in [['Tab点击 UV',data?.recommendation?.front_tab_uv],['内容曝光 UV',data?.recommendation?.content_exposure_uv],['内容点击 UV',data?.recommendation?.content_click_uv],['内容点击率',data?.recommendation?.content_click_rate]]" :key="String(item[0])" class="metric-item"><div class="metric-label"><span>{{item[0]}}</span><small>Quick BI 首页猜你喜欢</small></div><strong>{{String(item[0]).includes('率')?pct(item[1] as number):num(item[1] as number)}}</strong></article></section><section class="content-grid"><article class="panel"><div class="panel-head"><div><h2>曝光与点击趋势</h2><p>猜你喜欢首页真实UV</p></div></div><Chart class="conversion-chart" :option="guessChart"/></article><article class="panel ranking-note"><div class="panel-head"><div><h2>消费承接质量</h2><p>独立质量指标</p></div></div><dl><div><dt>首帧整体转化率</dt><dd>{{pct(data?.recommendation?.ff_play_convert_rate)}}</dd></div><div><dt>播放转化率</dt><dd>{{pct(data?.recommendation?.play_convert_rate)}}</dd></div><div><dt>5分钟整体转化率</dt><dd>{{pct(data?.recommendation?.play_5min_rate_uv)}}</dd></div><div><dt>人均播放时长</dt><dd>{{data?.recommendation?.avg_time_uv??'--'}}</dd></div></dl></article></section></template>
<el-drawer v-model="drawer" title="首页运营来源与口径" size="440px"><div class="source-drawer"><section><span>当前数据源</span><strong>{{tab==='channel'?data?.meta.channel.source:data?.meta.recommendation.source}}</strong></section><section><span>原始字段</span><div class="field-tags"><code v-for="f in (tab==='channel'?data?.meta.channel.original_fields:data?.meta.recommendation.original_fields)" :key="f">{{f}}</code></div></section><p>首页频道与猜你喜欢来自不同接口，只在各自标签页展示，不跨源拼接。猜你喜欢页面固定核对为“首页”。</p></div></el-drawer></main></template>
