<script setup lang="ts">
import {computed,defineAsyncComponent,onMounted,reactive,ref} from "vue";
import {Download,InfoFilled,RefreshRight} from "@element-plus/icons-vue";
import {useRoute,useRouter} from "vue-router";
import {fetchResources,type ResourcePayload,type ResourceType} from "../api/resourcePlacement";
import {useThemeStore} from "../stores/theme";
const Chart=defineAsyncComponent(()=>import("../components/ContentRankingChart.vue"));const route=useRoute(),router=useRouter();
const defaults:Record<ResourceType,string>={section:"2026-09-15",banner:"2026-08-04",popup:"2026-09-15"};
const type=ref<ResourceType>(["section","banner","popup"].includes(String(route.query.type))?route.query.type as ResourceType:"section");
const theme=useThemeStore();
const state=reactive({date:typeof route.query.date==="string"?route.query.date:defaults[type.value],page:1,pageSize:15,sort:type.value==="popup"?"play_uv":"click_uv",direction:"desc",search:""});
const data=ref<ResourcePayload|null>(null),loading=ref(false),error=ref(""),drawer=ref(false);const nf=new Intl.NumberFormat("zh-CN");
const labels={section:"首页板块",banner:"Banner",popup:"弹窗"};function num(v:number|null|undefined){return v==null?"--":nf.format(v)}function pct(v:number|null|undefined){return v==null?"--":`${(v*100).toFixed(2)}%`}
async function load(){loading.value=true;error.value="";router.replace({query:{type:type.value,date:state.date,page:String(state.page),sort:state.sort}});try{data.value=await fetchResources({resource_type:type.value,date:state.date,page:state.page,page_size:state.pageSize,sort:state.sort,direction:state.direction,search:state.search||undefined})}catch(e){error.value="资源位数据加载失败，请确认快照已经导入。";console.error(e)}finally{loading.value=false}}
function switchType(value:ResourceType){type.value=value;state.date=defaults[value];state.page=1;state.sort=value==="popup"?"play_uv":"click_uv";state.search="";load()}
function pageChange(value:number){state.page=value;load()}function sort(value:string){state.sort=value;state.page=1;load()}
function exportCsv(){const params=new URLSearchParams({resource_type:type.value,date:state.date,sort:state.sort,direction:state.direction});if(state.search)params.set("search",state.search);const link=document.createElement("a");link.href=`/api/v1/resource-placements/export?${params}`;link.download=`${labels[type.value]}-${state.date}.csv`;document.body.appendChild(link);link.click();link.remove()}
const chartOption=computed(()=>({animationDuration:220,color:[theme.current.primary],grid:{left:150,right:36,top:14,bottom:28},tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},xAxis:{type:"value",axisLabel:{color:"#7a8492"},splitLine:{lineStyle:{color:"#eef1f4"}}},yAxis:{type:"category",data:data.value?.items.slice(0,10).reverse().map(x=>x.name.length>12?x.name.slice(0,12)+"…":x.name)??[],axisLabel:{color:"#5c6370"}},series:[{type:"bar",barMaxWidth:18,data:data.value?.items.slice(0,10).reverse().map(x=>type.value==="popup"?x.play_uv:x.click_uv)??[],itemStyle:{borderRadius:[0,4,4,0]}}]}));
onMounted(load);
</script>
<template><main class="main-content page-stack resource-page"><header class="page-intro"><div><h2>资源位运营</h2><p>首页板块、Banner 与弹窗效果统一入口，各自保留原始口径。</p></div><button class="source-button" @click="drawer=true"><el-icon><InfoFilled/></el-icon>数据说明</button></header>
<section class="filter-bar ranking-filter" aria-label="资源位筛选"><div class="ranking-tabs" role="tablist"><button v-for="value in (['section','banner','popup'] as ResourceType[])" :key="value" role="tab" :aria-selected="type===value" :class="{active:type===value}" @click="switchType(value)">{{labels[value]}}</button></div><label><span>数据日期</span><el-date-picker v-model="state.date" type="date" value-format="YYYY-MM-DD"/></label><label><span>名称搜索</span><el-input v-model="state.search" clearable placeholder="输入名称" @keyup.enter="load"/></label><el-button type="primary" :loading="loading" @click="load"><el-icon><RefreshRight/></el-icon>更新视图</el-button><div class="freshness"><span class="status-dot"></span><div><b>{{labels[type]}}真实快照</b><small>{{data?.meta.source??'--'}}</small></div></div></section>
<el-alert v-if="error" :title="error" type="error" show-icon :closable="false"/>
<section class="ranking-summary-grid"><article class="metric-item"><div class="metric-label"><span>曝光 UV</span><small>当前日期合计</small></div><strong>{{num(data?.summary.exposure_uv)}}</strong></article><article class="metric-item"><div class="metric-label"><span>点击 UV</span><small>当前日期合计</small></div><strong>{{num(data?.summary.click_uv)}}</strong></article><article class="metric-item"><div class="metric-label"><span>点击率</span><small>点击 UV / 曝光 UV</small></div><strong>{{pct(data?.summary.ctr)}}</strong></article><article class="metric-item"><div class="metric-label"><span>{{type==='popup'?'有效播放 UV':'记录数'}}</span><small>{{type==='popup'?'真实有效播放':'当前筛选结果'}}</small></div><strong>{{type==='popup'?num(data?.summary.play_uv):`${data?.pagination.total??0} 条`}}</strong></article></section>
<section class="panel"><div class="panel-head"><div><h2>{{type==='popup'?'有效播放':'点击'}}贡献 Top10</h2><p>基于当前筛选结果的服务端排序</p></div><span>{{state.date}}</span></div><Suspense v-if="data?.items.length"><Chart class="resource-chart" :option="chartOption"/></Suspense><div v-else-if="!loading" class="empty-state"><strong>当前日期暂无记录</strong></div></section>
<section class="panel ranking-detail-panel"><div class="panel-head ranking-table-head"><div><h2>{{labels[type]}}明细</h2><p>服务端分页；导出当前日期和搜索条件，最多 5,000 条</p></div><div class="ranking-table-actions"><el-button size="small" @click="exportCsv"><el-icon><Download/></el-icon>导出 CSV</el-button><div class="ranking-sort"><span>排序</span><button :class="{active:state.sort==='exposure_uv'}" @click="sort('exposure_uv')">曝光 UV</button><button :class="{active:state.sort==='click_uv'}" @click="sort('click_uv')">点击 UV</button><button :class="{active:state.sort==='ctr'}" @click="sort('ctr')">点击率</button><button v-if="type==='popup'" :class="{active:state.sort==='play_uv'}" @click="sort('play_uv')">有效播放 UV</button></div></div></div><div v-loading="loading" class="table-wrap"><table class="client-table resource-table"><thead><tr><th>名称</th><th>频道/位置</th><th>客户端</th><th>曝光 PV</th><th>曝光 UV</th><th>点击 PV</th><th>点击 UV</th><th>点击率</th><th v-if="type==='popup'">跳转 UV</th><th v-if="type==='popup'">有效播放 UV</th><th v-if="type==='popup'">有效播放率</th></tr></thead><tbody><tr v-for="(item,index) in data?.items" :key="`${item.name}-${index}`"><td><strong>{{item.name}}</strong></td><td>{{item.channel||item.position||'--'}}</td><td>{{item.client||'--'}}</td><td>{{num(item.exposure_pv)}}</td><td>{{num(item.exposure_uv)}}</td><td>{{num(item.click_pv)}}</td><td>{{num(item.click_uv)}}</td><td>{{pct(item.ctr)}}</td><td v-if="type==='popup'">{{num(item.jump_uv)}}</td><td v-if="type==='popup'">{{num(item.play_uv)}}</td><td v-if="type==='popup'">{{pct(item.play_rate)}}</td></tr></tbody></table></div><div class="table-footer"><el-pagination background layout="prev, pager, next, total" :current-page="state.page" :page-size="state.pageSize" :total="data?.pagination.total??0" @current-change="pageChange"/></div></section>
<el-drawer v-model="drawer" title="资源位来源与口径" size="440px"><div class="source-drawer"><section><span>当前模块</span><strong>{{labels[type]}}</strong></section><section><span>数据源</span><strong>{{data?.meta.source??'--'}}</strong></section><section><span>原始字段</span><div class="field-tags"><code v-for="field in data?.meta.original_fields" :key="field">{{field}}</code></div></section><p v-if="data?.meta.limitations.length">{{data.meta.limitations.join('；')}}，保持空值，不使用相近字段推算。</p><p>板块、Banner、弹窗分别来自独立接口，只在各自标签页内汇总。</p></div></el-drawer></main></template>
